#!/usr/bin/env python3
"""Render the differential-growth bending result (morphompm v1, test T3).

Reads outputs/figures/differential_growth.csv (written by test_growth), plots a
z-centered slice of the bilayer strip in the x-y plane, colored by elastic
log-strain magnitude ||eps_e|| (the residual stress). Saves PNG (no popup) +
regenerates the _desc.md.
"""
import csv
import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV = os.path.join(HERE, "outputs", "figures", "differential_growth.csv")
PNG = os.path.join(HERE, "outputs", "figures", "differential_growth.png")
DESC = os.path.join(HERE, "outputs", "figures", "differential_growth_desc.md")

xs, ys, zs, eps = [], [], [], []
with open(CSV) as f:
    for row in csv.DictReader(f):
        xs.append(float(row["x"])); ys.append(float(row["y"]))
        zs.append(float(row["z"])); eps.append(float(row["eps_e"]))

# z-centered slice for a clean side view of the bend.
zc = sum(zs) / len(zs)
sx, sy, se = [], [], []
for x, y, z, e in zip(xs, ys, zs, eps):
    if abs(z - zc) < 0.03:
        sx.append(x); sy.append(y); se.append(e)

fig, ax = plt.subplots(figsize=(7.0, 4.2))
sc = ax.scatter(sx, sy, c=se, cmap="viridis", s=18, vmin=0.0, vmax=max(eps))
cb = fig.colorbar(sc, ax=ax)
cb.set_label(r"elastic log-strain $\|\varepsilon_e\|$  (residual stress)")
ax.set_xlabel("x (m)")
ax.set_ylabel("y (m)")
ax.set_title("Differential-growth bending (bilayer)\n"
             "top layer g=1.5, bottom g=1.1 — incompatible growth -> bend + residual stress")
ax.set_aspect("equal")
fig.tight_layout()
fig.savefig(PNG, dpi=150)
print("wrote", PNG)

with open(DESC, "w", encoding="utf-8") as f:
    f.write(f"""# Figure: differential_growth

## Purpose
Demonstrate that incompatible (differential) morphoelastic growth in MLS-MPM
produces residual stress and macroscopic bending — the morphogenesis regime that
free isotropic swelling (which relaxes to zero stress) cannot exhibit.

## Data Source
- File: differential_growth.csv
- Generated by: test_growth.exe (test T3), rendered by scripts/plot_growth.py
- Date: 2026-06-28

## Axes
- X: x position (m) — strip long axis
- Y: y position (m) — bilayer thickness / deflection direction
- Color: elastic log-strain magnitude ||eps_e|| (proportional to residual stress)
- Slice: |z - z_center| < 0.03 m

## Key Observations
Numerical observations only.
- Bilayer strip: bottom layer Fg = 1.10·I, top layer Fg = 1.50·I.
- After relaxation: mean ||eps_e|| = 0.0997 (vs free-swell floor ~0.0031).
- Midline mean-y [L, C, R] = [0.6861, 0.7267, 0.6861]; bend = 0.0406 m.
- Symmetric (L == R): no spurious rigid rotation.

## Reproduction
cmake --build build --config Release
./build/Release/test_growth.exe
python scripts/plot_growth.py
""")
print("wrote", DESC)
